_target_: src.models.solar_module.SolarModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001


scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 3

net:
  _target_: src.models.components.solar.SOLAR
  name: "beomi/Llama-3-Open-Ko-8B-Instruct-preview"
  lora_module: ["self_attn.q_proj", "self_attn.k_proj"]

# compile model for faster training with pytorch 2.0
compile: false
